//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShelvesAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eShelvesEntities : DbContext
    {
        public eShelvesEntities()
            : base("name=eShelvesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int usp_addAutorKategorija(Nullable<int> aUID, Nullable<int> kATID)
        {
            var aUIDParameter = aUID.HasValue ?
                new ObjectParameter("AUID", aUID) :
                new ObjectParameter("AUID", typeof(int));
    
            var kATIDParameter = kATID.HasValue ?
                new ObjectParameter("KATID", kATID) :
                new ObjectParameter("KATID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_addAutorKategorija", aUIDParameter, kATIDParameter);
        }
    
        public virtual int usp_addKnjigaKategorija(Nullable<int> kNJID, Nullable<int> kATID)
        {
            var kNJIDParameter = kNJID.HasValue ?
                new ObjectParameter("KNJID", kNJID) :
                new ObjectParameter("KNJID", typeof(int));
    
            var kATIDParameter = kATID.HasValue ?
                new ObjectParameter("KATID", kATID) :
                new ObjectParameter("KATID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_addKnjigaKategorija", kNJIDParameter, kATIDParameter);
        }
    
        public virtual int usp_RemoveAutorKategorijas(Nullable<int> aUID)
        {
            var aUIDParameter = aUID.HasValue ?
                new ObjectParameter("AUID", aUID) :
                new ObjectParameter("AUID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RemoveAutorKategorijas", aUIDParameter);
        }
    
        public virtual int usp_RemoveKnjigaKategorijas(Nullable<int> kNJID)
        {
            var kNJIDParameter = kNJID.HasValue ?
                new ObjectParameter("KNJID", kNJID) :
                new ObjectParameter("KNJID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RemoveKnjigaKategorijas", kNJIDParameter);
        }
    }
}
